name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set image tag
      id: set_tag
      run: echo "tag=model-registry:latest" >> $GITHUB_OUTPUT

    - name: Build Docker image
      run: docker build -t model-registry:latest .

